import Head from "next/head";
import NFTCollectionContainer from "@Containers/NFTCollectionContainer/NFTCollectionContainer";

export default function NFTCollectionPage() {
  return (
    <>
      <Head>
        <title>NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <>
          <NFTCollectionContainer />
        </>
      </main>
    </>
  );
}
