import Head from "next/head";
import NFTDetailContainer from "@Containers/NFTDetailContainer/NFTDetailContainer";

export default function NFTDetailPage() {
  return (
    <>
      <Head>
        <title>NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <>
          <NFTDetailContainer />
        </>
      </div>
    </>
  );
}
