import Head from "next/head";
import CreateNFTContainer from "@Containers/CreateNFTContainer/CreateNFTContainer";
import LoadingPage from "@Components/LoadingPage/LoadingPage";
import { ReactElement, useContext } from "react";
import { AppContext } from "@Store/index";
import ModLayout from "@Layouts/ModLayout/ModLayout";

export default function ModPage() {
  const web3Context = useContext(AppContext);
  return (
    <>
      <Head>
        <title>NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}

ModPage.getLayout = function getLayout(page: ReactElement) {
  return <ModLayout>{page}</ModLayout>;
};
