import Head from "next/head";
import CreateCollectionContainer from "@Containers/CreateCollectionContainer/CreateCollectionContainer";

export default function CreateCollectionPage() {
  return (
    <>
      <Head>
        <title>NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <>
          <CreateCollectionContainer />
        </>
      </div>
    </>
  );
}
